### ISSUE TITLE
v1.1 error: mv: cannot stat `*.faa.scg': No such file or directory

### ISSUE THREAD

**Issue by snayfach** [cmks/DAS_Tool#13]
I'm running into an error running v1.1 on the example dataset. Here's the error I get with usearch:
```
./DAS_Tool -i sample_data/sample.human.gut_concoct_scaffolds2bin.tsv,sample_data/sample.human.gut_maxbin2_scaffolds2bin.tsv,sample_data/sample.human.gut_metabat_scaffolds2bin.tsv,sample_data/sample.human.gut_tetraESOM_scaffolds2bin.tsv -l concoct,maxbin,metabat,tetraESOM -c sample_data/sample.human.gut_contigs.fa -o sample_output/DASToolRun -t 30
predicting genes using prodigal
identifying single copy genes using usearch
mv: cannot stat `sample_output/DASToolRun_proteins.faa.scg': No such file or directory
running DAS Tool with 30 threads
Execution halted
```

And the same error with blast:
```
./DAS_Tool -i sample_data/sample.human.gut_concoct_scaffolds2bin.tsv,sample_data/sample.human.gut_maxbin2_scaffolds2bin.tsv,sample_data/sample.human.gut_metabat_scaffolds2bin.tsv,sample_data/sample.human.gut_tetraESOM_scaffolds2bin.tsv -l concoct,maxbin,metabat,tetraESOM -c sample_data/sample.human.gut_contigs.fa -o sample_output/DASToolRun -t 30 --search_engine blast
predicting genes using prodigal
identifying single copy genes using blast
mv: cannot stat `sample_output/DASToolRun_proteins.faa.scg': No such file or directory
running DAS Tool with 30 threads
Execution halted
```

I do not get this error with v1.0. v1.0 completes this step successfully, but runs into a different error at a later step.

**Comment by snayfach** [comment]
I noticed that there was a new commit yesterday to fix this issue. After cloning the latest version, this is the new error I get with v1.1:

```
./DAS_Tool -i sample_data/sample.human.gut_concoct_scaffolds2bin.tsv,sample_data/sample.human.gut_maxbin2_scaffolds2bin.tsv,sample_data/sample.human.gut_metabat_scaffolds2bin.tsv,sample_data/sample.human.gut_tetraESOM_scaffolds2bin.tsv -l concoct,maxbin,metabat,tetraESOM -c sample_data/sample.human.gut_contigs.fa -o sample_output/DASToolRun -t 30
predicting genes using prodigal
identifying single copy genes using usearch
running DAS Tool with 30 threads
evaluating bin-sets
starting bin selection from  0  bins

Execution halted
```

**Comment by snayfach** [comment]
I reran it with the debug flag, and here is a more detailed error message:

```
predicting genes using prodigal
identifying single copy genes using usearch
running DAS Tool with 30 threads
evaluating bin-sets
starting bin selection from  0  bins
Error in file(file, "rt") : cannot open the connection
Calls: cherry_pick -> read.table -> file
In addition: Warning messages:
1: In max(bin_summary$score) :
  no non-missing arguments to max; returning -Inf
2: In file(file, "rt") :
  cannot open file 'sample_output/DASToolRun_DASTool_summary.txt': No such file or directory
Execution halted
```

I noticed a commented line of code on line #292 in the file `cherry_pick.R` which writes to `paste(output_basename,'_DASTool_summary.txt',sep='')`. Uncommenting this did not solve the issue for me however

**Comment by snayfach** [comment]
Looking at the code now...

The above error is caused by taking a max over a vector of length zero. The data frame `bin_summary` is reduced from 20 rows to 0 rows after this is executed:  
`bin_summary <- bin_summary[ bin_summary$maxRatio > internal_ratio_threshold, ]`

I commented this line out, but the second error remains. I'm not going to try it fix this any further. Hopefully a bug fix is on the way.

Thanks,
Stephen

**Comment by snayfach** [comment]
Turns out the issue caused by the wrong Prodigal (2.5 instead of 2.6)

**Comment by jvollme** [comment]
I have the same problem. Using the correct version of prodigal (v.2.6.3). But the "scg" files should not be created by prodigal anyway. That should be part of the following "ruby" step, right?
So How exactly did you solve this?
In my case, it turns out that the scg files have been created in the "sample_output" folder of the DAS_tool installation folder instead of the current working directory. 
So it SEEMS that probably i could solve this by changing the lines (e.g. Line295) that are supposed to rename the scg files within the working directory from: 
  ```mv $proteins\.scg $bscg``` 
to 
```mv ${DIR}/sample_output/$proteins\.scg $bscg```
But if this was to actually be the problem, everybody should be experiencing this, right?

**Comment by msbufz** [comment]
I am also interested and how you did to solve this problem as I am tackling the same issue.

**Comment by jvollme** [comment]
In my case, the problem was that the shebang of the ruby scripts called by the DAStool pipeline at this point were not suitable for my system/setup. They pointed to the global ruby installation, installed under /usr/bin (which was an old version, and which I had no controll over, since I work on a public server and have to install all my personal dependencies under a local conda environment).
Changing the shebang to "'!/usr/bin/env ruby" fixed the problem for me.
See also this thread for details: #15

**Comment by nick-youngblut** [comment]
I'm running das_tool with prodigal 2.6.3, and from looking at the das_tool code, it appears that the shabang lines for the ruby scripts have been changed to `#!/usr/bin/env ruby`. Still, I'm seemingly getting the error as reported above:

```
diamond v0.9.25.126 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

/ebio/abt3_projects/bin/llmga/.snakemake/conda/5d764adc/bin/DAS_Tool: line 241: usearch: command not found
Running DAS Tool using 12 threads.
predicting genes using Prodigal V2.6.3: February, 2016
diamond v0.9.25.126 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

identifying single copy genes using diamond version 0.9.25
mv: cannot stat '/ebio/abt3_projects/DAS_Tool/bins_proteins.faa.scg': No such file or directory
single copy gene prediction using diamond failed. Aborting
```

This only seems to happen with some das_tool jobs (certain datasets) and not others.

**Comment by yanhui09** [comment]
@jvollme mention #https://github.com/cmks/DAS_Tool/issues/13#issuecomment-359875950 is corrct. It's probably due to the "ruby" conflicts between the `base` and `conda` environment. I use a public server, which has ruby installed already. Although in a conda environment `ruby` points to the correct `bin path`, it collaps when I call it. I know little about ruby, so I can't give more explanation about this.

As I have limited control of the public sever, my solution is to solely remove the `ruby` in the `conda` environment, and use the default one with the server. (It may have some issues with nodes without `ruby`, which is decided by how the cluster is set up) 
Something like:
```
conda remove ruby --force
```
