### ISSUE TITLE
Issue if the memory requirement for usearch is too high

### ISSUE THREAD

**Issue by michoug** [cmks/DAS_Tool#34]
Hi,

I used your tool and I got this error with the usearch option

`cannot stat sample_output/Test_proteins.faa.scg: No such file or directory`

I investigated as it was working before and realized that when I just run 

`ruby ~/DAS_Tool-master/src/scg_blank_usearch.rb usearch Test_proteins.faa ~/DAS_Tool-master/db/bac.all.faa ~/DAS_Tool-master/db/bac.scg.faa ~/DAS_Tool-master/db/bac.scg.lookup`

I got this error

```
00:07 1.0Gb   100.0% Reading Test_proteins.faa
00:15 1.0Gb   100.0% Masking (fastamino)        
00:32 1.0Gb   100.0% Word stats         
00:32 3.4Gb   100.0% Alloc rows
01:39 3.7Gb   100.0% Build index
01:41 3.7Gb   100.0% Rows       
01:41 3.7Gb  Buffers (2959751 seqs)


usearch -makeudb_ublast Test_proteins.faa -output Test_proteins.faa.udb

---Fatal error---
Memory limit of 32-bit process exceeded, 64-bit build required
makeblastdb did not work for Test_proteins.faa, please check your input file
```

This is due to the large proteins file (~900 Mb) and the "free" version of usearch.
It maybe worth it to try to put another error message, if possible?

**Comment by nick-youngblut** [comment]
That's actually somewhat of a small proteins file. A metagenome assembly of 100's of samples will likely generate a 10's of Gb file. DAS_Tool then requires >= 1TB of memory, and thus doesn't scale well for moderate to large metagenome datasets. That's a warning for anyone who tries.

**Comment by cmks** [comment]
Thanks for pointing this out! I'll add a note about the 32bit version of usearch.
For big datasets, I recommend using DIAMOND or usearch 64bit. Blast of course is also an option but might be pretty slow on GB scale protein files.

@nick-youngblut, I don't know what kind of samples you are working with but you might want to consider assembling and binning them separately. My experience is that the results in terms of assembly and bin quality turned out to be much better. 
For de-replicating bins from multiple samples I can recommend drep (https://github.com/MrOlm/drep).
