### ISSUE TITLE
General questions: is it necessary to pre select potentionally high quality bin sets as input for DAS tool? 

### ISSUE THREAD

**Issue by fulaibaowang** [cmks/DAS_Tool#65]
Hello,

I performed binning in MAXBIN2, CONCOCT etc... and got the bins (MAGs). Would you suggest use all the bins as input for DAS tool, or would you set a completeness threshold for the bins that go into the DAS tool pipeline?

Cheers,
Yun

**Comment by cmks** [comment]
Hi Yun,
There's no need for pre-filtering as DAS Tool selects bins based on an internally performed completeness and contamination estimation using marker genes. Dependent on your used `--score_threshold` setting, bins with low completeness will not be reported in the output.

**Comment by fulaibaowang** [comment]
Thanks!

**Comment by fulaibaowang** [comment]
Hi, thank you for your quick response! I want to ask one more question -- will eukaryotic bins be reported by DASTool?

**Comment by cmks** [comment]
No, eukaryotic bins are not reported by DASTool. For that I recommend running EukRep (https://github.com/patrickwest/EukRep).

**Comment by MrCrotalusatrox** [comment]
Following this question, what I really want is DasTool only to dereplicate the MAGs using the quality information to guide which MAGs are best out of a set of equivalent MAGs across binning tools. But, I still want it to output all of the MAGs that are poor quality...so still dereplicated, just no quality filtering, if that makes sense? The reason is that we're working with reduced genomes that may get thrown out by traditional completeness scoring. I want to dereplicate between binning algorithms, but do my own quality filtering later. Could I achieve this by setting --score_threshold to zero?
