### ISSUE TITLE
Incorrect "number of bins to start with" reported in log

### ISSUE THREAD

**Issue by patriciatran** [cmks/DAS_Tool#72]
Hi,

I am using DASTool v. 1.1.3 from a Conda environment. 
I have 4 folders with these number of bins in each, which I'd like to use DASTool to refine.
```
Metabat 1: 130 bins
Metabat 2: 188 bins
Maxbin 2: 176 bins
JGI bins: 25
```

I ran dastool on this set:
```
Metabat 1: 130 bins
Metabat 2: 188 bins
Maxbin 2: 176 bins
```
but the log says:

```
starting bin selection from 441 bins
bin selection complete: 90 bins above score threshold selected.
```

Which does not match the sum of bins (130+188+176 = 494) 

Then I ran dastool on this set:
```
Metabat 1: 130 bins
Metabat 2: 188 bins
Maxbin 2: 176 bins
JGI bins: 25
```
and the log says:
```
starting bin selection from 466 bins
bin selection complete: 90 bins above score threshold selected.
```
 
Which then again does not match the initial number of bins, but is 25 more bins that I started with (probably from the jgi_bins folder). In both cases, it gives me the same 90 in the end.

I also tried renaming bins in each subfolder (metabat1, metabat2, maxbin2, jgi_mags) to ensure all 519 mags had unique names. but the logs still said:
```
starting bin selection from 466 bins
bin selection complete: 90 bins above score threshold selected.
```

I looked at all my scaf2bins.tsv files and they were ok, the correct number of MAGS in the second column was there.

Have you encountered this mismatch before? What can I do differently? Since in each case I end up with 90 mags, is it just a matter of the mags not being reported correctly, or are they not all used (read in as input) for the program?

Thank you,

Patricia

**Comment by patriciatran** [comment]
PS: If that is of any relevance, the numbers of rows in the `.eval` files matches the number of bins I have in my initial mag folders.

**Comment by patriciatran** [comment]
Hello again,
After having looked at the `.eval` files, I noticed that the MAGS for which the binscore = 0 were removed from the "bins considered".
For example, using the example above:
```
Total mags	519
Binscore = 0	53
Binscore < 0	14
Bins considered (log) (519-53)	466
```

Can you tell me more about the significance of remove the `binScore == 0` instead of `binScore <= 0`?

Thank you,

Patricia

**Comment by cmks** [comment]
Hi Patricia,
You're right, bins with a score of zero are not part of the output and are not counted in the initial number. More precisely it is bins without any single copy genes resulting in a score of zero that are excluded. This is because DAS Tool can't distinguish between bins without any single copy genes as it can't estimate their completeness or contamination. Furthermore, their score will always stay zero even if any contigs are removed during the selection process.

Bins with a negative bin score usually have a high number of redundant single copy genes indicating a high level of contamination. However, it is possible that the contamination part of a bin is removed if DAS Tool is able to select a second bin to which the contamination belongs to. In this case the score of the first bin will increase and could potentially be selected too.

I hope this answers your question.

Christian
