### ISSUE TITLE
Error in vecseq

### ISSUE THREAD

**Issue by dyxstat** [cmks/DAS_Tool#84]
Hi,

I ran the DASTool and the execution halted with the following returns:

Dereplicating, aggregating, and scoring bins
Error in vecseq(f__, len__, if (allow.cartesian || notjoin || !anyDuplicated(f__,  :
  Join results in 150236 rows; more than 126193 = nrow(x)+nrow(i). Check for duplicate key values in i each of which join to the same group in x over and over again. If that's ok, try b
y=.EACHI to run j for each group to avoid the large allocation. If you are sure you wish to proceed, rerun with allow.cartesian=TRUE. Otherwise, please search for this error message in
the FAQ, Wiki, Stack Overflow and data.table issue tracker for advice.
Calls: cherry_pick -> [ -> [.data.table -> vecseq
Execution halted

I am not sure what happened since I try some toy examples and DASTool can work. 

Best,
Yancey

**Comment by Somebodyatthdoor** [comment]
Hi,
I am also getting this error with one of my samples and I'm having trouble understanding what is causing it. 

Error:
"Error in vecseq(f__, len__, if (allow.cartesian || notjoin || !anyDuplicated(f__,  :
  Join results in 44655 rows; more than 41974 = nrow(x)+nrow(i). Check for duplicate key values in i each of which join to the same group in x over and over again. If that's ok, try by=.EACHI to run j for each group to avoid the large allocation. If you are sure you wish to proceed, rerun with allow.cartesian=TRUE. Otherwise, please search for this error message in the FAQ, Wiki, Stack Overflow and data.table issue tracker for advice.
Calls: cherry_pick -> [ -> [.data.table -> vecseq
Execution halted"

I've attached the input tsv files and the log file. 

Cheers,
Laura
[dast_tool_sample_6737_HOM_CTRL_hifiasm.zip](https://github.com/cmks/DAS_Tool/files/9533797/dast_tool_sample_6737_HOM_CTRL_hifiasm.zip)

**Comment by Pablo-Aja-Macaya** [comment]
Hello, same error here on version 1.1.4 with a clean conda environment (Ubuntu), and only in some samples. It worked when downgrading to 1.1.3 using the same samples, so maybe it has something to do with that R dependency?

**Comment by cmks** [comment]
Hi all, thanks for reporting this bug. The error is cause by an internal R library and is supposed to be a protection mechanism against excessive memory usage. However, for the given use case it needs to be disabled. I've just pushed a fix for this to the master branch.

@Somebodyatthdoor thanks for sharing the files with me. Can you also please upload your `*bacteria.scg` and `*archaea.scg` tables? I'd like to check if there are any other issues before creating a new release.

**Comment by Somebodyatthdoor** [comment]
> Hi all, thanks for reporting this bug. The error is cause by an internal R library and is supposed to be a protection mechanism against excessive memory usage. However, for the given use case it needs to be disabled. I've just pushed a fix for this to the master branch.
> 
> @Somebodyatthdoor thanks for sharing the files with me. Can you also please upload your `*bacteria.scg` and `*archaea.scg` tables? I'd like to check if there are any other issues before creating a new release.

Sure, no problem. Files are attached below. 
[das_tool_6737_HOM_CTRL_hifiasm_scg_files.zip](https://github.com/cmks/DAS_Tool/files/9546937/das_tool_6737_HOM_CTRL_hifiasm_scg_files.zip)

**Comment by cmks** [comment]
This bug is fixed in [v1.1.5](https://github.com/cmks/DAS_Tool/releases/tag/1.1.5)
